Repository TeamTheGenius/TeamTheGenius_Web, pull requests merged in 2024-02, with the labels that each got.

#120 Feature/115 progress complete list
  src/assets/icon/arrow-right.svg
  src/assets/icon/human-icon.svg
  src/components/Main/MyChallenge/MyChallengeHeader/MyChallengeHeader.tsx
  src/components/Main/MyChallenge/MyChallengeLabel/MyChallengeLabel.tsx
  src/components/Main/MyChallenge/MyChallengeLinkWrap/MyChallengeLinkWrap.tsx
  src/components/Main/MyChallenge/MyChallengePic/MyChallengePic.tsx
  src/components/Main/MyChallenge/MyChallengeTitle/MyChallengeTitle.tsx
  src/components/Main/MyChallenge/MyChallengeWrap/MyChallengeWrap.tsx
  src/constants/path.ts
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
  src/pages/MyChallenge/MyChallengeStyle.css
  tailwind.config.js
Labels: enhancement

#121 Feature/119 challenge detail UI
  src/App.tsx
  src/assets/icon/black-person-icon.svg
  src/components/ChallengeDetail/BackIcon/BackIcon.tsx
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/components/ChallengeDetail/CoreInformation/CoreInformation.tsx
  src/components/ChallengeDetail/Heart/Heart.tsx
  src/components/ChallengeDetail/Image/Image.tsx
  src/components/ChallengeDetail/Information/Information.tsx
  src/components/ChallengeDetail/Line/Line.tsx
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/common/Button.tsx
  src/components/common/ChallengeItem/ChallengeItem.tsx
  src/components/common/MobCard.tsx
  src/components/common/VerticalChallengeItems/VerticalChallengeItems.tsx
  src/constants/path.ts
  src/data/allChallengeData.ts
  src/pages/ChallengeDetail/ChallengeDetail.tsx
  src/pages/NewChallenge/NewChallenge.tsx
  src/pages/PopularChallenge/PopularChallenge.tsx
  src/pages/SuggestionChallenge/SuggestionChallenge.tsx
Labels: enhancement, refactor

#124 Bugfix/122 solve mychallenge bug
  src/components/ChallengeDetail/Image/Image.tsx
  src/components/Main/MyChallenge/MyChallengeLinkWrap/MyChallengeLinkWrap.tsx
  src/components/Main/MyChallenge/MyChallengePic/MyChallengePic.tsx
  src/components/Main/MyChallenge/MyChallengeTitle/MyChallengeTitle.tsx
  src/components/common/ChallengeItem/ChallengeItem.tsx
  src/constants/path.ts
  src/data/allChallengeData.ts
  src/pages/ChallengeDetail/ChallengeDetail.tsx
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
Labels: enhancement, refactor

#127 로그인 jwt api 연동 및 가입페이지 UI 수정
  src/App.tsx
  src/apis/postJWTApi.ts
  src/apis/postSignUpApi.ts
  src/components/Interest/InterestButton/InterestBtn.tsx
  src/components/Interest/InterestHeader/InterestHeader.tsx
  src/components/SignUp/SignUpForm/SignUpForm.tsx
  src/components/SignUp/SignUpForm/SignUpName/SignUpName.tsx
  src/constants/path.ts
  src/pages/Auth/Auth.tsx
  src/pages/Interest/Interest.tsx
  src/pages/LogIn/LogIn.tsx
  src/pages/signUp/signUpStyle.css
Labels: enhancement, refactor

#131 feat: loading-error UI 완성
  src/assets/icon/loading.png
  src/components/Error/ErrorHeader/ErrorHeader.tsx
  src/components/common/Loading.tsx
  src/components/common/Loding/Loading.tsx
  src/components/common/Loding/loading.css
  src/pages/error/Error.tsx
  src/pages/error/errorStyle.css
Labels: enhancement

#132 error 수정
  src/pages/error/Error.tsx
Labels: refactor

#136 Feature/135 challengeitem reward
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/common/ChallengeItem/ChallengeItem.tsx
  src/components/common/VerticalChallengeItems/VerticalChallengeItems.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
Labels: enhancement, refactor

#141 Feat: 관심 목록 페이지 UI 완성
  src/App.tsx
  src/assets/icon/back-icon.svg
  src/components/common/ChallengeItem/ChallengeItem.tsx
  src/components/common/Header/Header.tsx
  src/constants/path.ts
  src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
Labels: enhancement

#143 Feature/142 home api
  package.json
  src/App.tsx
  src/apis/getLatestChallenge.ts
  src/apis/getPopularChallenge.ts
  src/apis/getRecommendedChallenge.ts
  src/apis/postJWTApi.ts
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/common/VerticalChallengeItems/VerticalChallengeItems.tsx
  src/pages/Auth/Auth.tsx
  src/pages/NewChallenge/NewChallenge.tsx
  src/pages/PopularChallenge/PopularChallenge.tsx
  src/pages/SuggestionChallenge/SuggestionChallenge.tsx
  yarn.lock
Labels: bug, enhancement

#144 Feat: 하단 네비게이션 버그 수정
  src/components/common/BottomNav/BottomNav.tsx
  src/components/common/VerticalChallengeItems/VerticalChallengeItems.tsx
  src/constants/path.ts
Labels: bug

#150 Feature/138 mypage mypage UI
  src/App.tsx
  src/assets/icon/gray-next-arrow.svg
  src/assets/icon/point-big-icon.svg
  src/assets/icon/point-small-icon.svg
  src/assets/icon/setting-icon.svg
  src/components/MyPage/MyPage/Header/Header.tsx
  src/components/MyPage/MyPage/LinkButtons/LinkButtons.tsx
  src/components/MyPage/MyPage/MyChallengeSummary/MyChallengeSummary.tsx
  src/components/MyPage/MyPage/MyPoint/MyPoint.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/MyPage/MyPage/SettingButton/SettingButton.tsx
  src/components/MyPage/MyPage/Temperature/Temperature.tsx
  src/components/common/Line/Line.tsx
  src/components/common/Profile/Profile.tsx
  src/constants/path.ts
  src/pages/Auth/Auth.tsx
  src/pages/Home/NewChallenge/NewChallenge.tsx
  src/pages/Home/PopularChallenge/PopularChallenge.tsx
  src/pages/Home/Search/Search.tsx
  src/pages/Home/SuggestionChallenge/SuggestionChallenge.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/MyPage/MyPage.tsx
  src/pages/MyPage/ProfileSetting/ProfileSetting.tsx
Labels: enhancement

#151 Feature/149 certification my current certification UI
  src/assets/icon/cross-icon.svg
  src/assets/icon/link-icon.svg
  src/assets/icon/red-check-icon.svg
  src/components/Certification/MyCurrentCertification/CurrentAchivementRate/CurrentAchivementRate.tsx
  src/components/Certification/MyCurrentCertification/MyAllCertificationLinkButton/MyAllCertificationLinkButton.tsx
  src/components/Certification/MyCurrentCertification/MyCertificationSummary/MyCertificationSummary.tsx
  src/components/Certification/MyCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/Home/HorizontalScroll/HorizontalScroll.tsx
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/common/CertificationResult/CertificationResult.tsx
  src/data/myCertificationResultData.ts
  src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx
  src/utils/getSlashDate.ts
Labels: enhancement

#153 Feat: 마이페이지 - 설정 메뉴 페이지 UI 완성
  src/App.tsx
  src/components/MyPage/MyPage/SettingButton/SettingButton.tsx
  src/components/MyPage/SettingMenu/LinkButton/LinkButton.tsx
  src/components/MyPage/SettingMenu/Title/Title.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/constants/path.ts
  src/pages/MyPage/ProfileSetting/ProfileSetting.tsx
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
Labels: enhancement

#154 Feat:어드민 토픽 api 및 인스턴스 api 연동
  package.json
  src/App.tsx
  src/apis/deleteAdminInstanceApi.ts
  src/apis/deleteAdminTopicApi.ts
  src/apis/getAdminDetailInstanceApi.ts
  src/apis/getAdminDetailTopicApi.ts
  src/apis/getAdminInstanceListApi.ts
  src/apis/getAdminListApi.ts
  src/apis/getAdminTopicListApi.ts
  src/apis/getCheckNicknameApi.ts
  src/apis/patchAdminInstanceEditApi.ts
  src/apis/patchAdminTopicEditApi.ts
  src/apis/postAdminInstanceApi.ts
  src/apis/postAdminTopicApi.ts
  src/components/Admin/AdminInstance/InstanceCreateModal/InstanceCreateModal.tsx
  src/components/Admin/AdminInstance/InstanceEditModal/InstanceEditModal.tsx
  src/components/Admin/AdminInstance/InstanceListComponent/InstanceListComponent.tsx
  src/components/Admin/AdminTopic/TopicCreateModal/TopicCreateModal.tsx
  src/components/Admin/AdminTopic/TopicEditModal/TopicEditModal.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/Main/MyChallenge/MyChallengePic/MyChallengePic.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/Loading/loading.css
  src/pages/Admin/AdminInstance/AdminInstance.tsx
  src/pages/Admin/AdminTopic/AdminTopic.tsx
  src/pages/Admin/adminType.ts
  src/utils/modalCard.tsx
  yarn.lock
Labels: enhancement

#157 Feat: 인증 페이지 - 나의 인증 현황 UI 완성
  src/App.tsx
  src/components/Certification/MyAllCurrentCertification/MyAllCertificationResult/MyAllCertificationResult.tsx
  src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx
  src/components/Certification/MyCurrentCertification/MyAllCertificationLinkButton/MyAllCertificationLinkButton.tsx
  src/components/Certification/MyCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/common/Profile/Profile.tsx
  src/constants/path.ts
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
Labels: enhancement

#159 Feature/158 participant current certification UI
  src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx
  src/components/Certification/MyCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/Certification/OthersCurrentCertification/OthersAllCertificationLinkButton/OthersAllCertificationLinkButton.tsx
  src/components/Certification/OthersCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/Certification/OthersCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/MyPage/MyPage/LinkButtons/LinkButtons.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Profile/Profile.tsx
  src/constants/path.ts
  src/data/othersCertificationResultData.ts
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
Labels: enhancement

#161 Feat: 인증 페이지 - 참가자 전체 인증 현황 UI 완성
  src/App.tsx
  src/components/Certification/OthersAllCurrentCertification/OthersAllCertificationResult/OthersAllCertificationResult.tsx
  src/components/Certification/OthersAllCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/Certification/OthersAllCurrentCertification/ReportButton/ReportButton.tsx
  src/components/Certification/OthersCurrentCertification/OthersAllCertificationLinkButton/OthersAllCertificationLinkButton.tsx
  src/components/Certification/OthersCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/common/Profile/Profile.tsx
  src/constants/path.ts
  src/data/othersCertificationResultData.ts
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
Labels: enhancement

#169 Feat: 홈 화면 api 연결
  package.json
  src/apis/getLatestChallenge.ts
  src/apis/getPopularChallenge.ts
  src/apis/getRecommendedChallenge.ts
  src/apis/postJWTApi.ts
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/common/ChallengeItem/ChallengeItem.tsx
  src/components/common/VerticalChallengeItems/VerticalChallengeItems.tsx
  src/hooks/useInfiniteScroll.ts
  src/pages/Home/NewChallenge/NewChallenge.tsx
  src/pages/Home/PopularChallenge/PopularChallenge.tsx
  src/pages/Home/SuggestionChallenge/SuggestionChallenge.tsx
  src/utils/makeBase64IncodedImage.ts
  yarn.lock
Labels: enhancement

#177 Feature/176 challenge detail api
  src/apis/getInstanceDetail.ts
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/components/ChallengeDetail/CoreInformation/CoreInformation.tsx
  src/components/ChallengeDetail/Image/Image.tsx
  src/pages/ChallengeDetail/ChallengeDetail.tsx
Labels: enhancement

#178 Feature/175 pr check page UI, Feature/174 github token UI
  src/App.tsx
  src/apis/patchAdminTopicEditApi.ts
  src/assets/icon/arrow-down.svg
  src/assets/icon/check-fail-icon.svg
  src/assets/icon/check-icon.svg
  src/assets/icon/check-success-icon.svg
  src/assets/icon/dia-icon.svg
  src/assets/icon/sign-icon.svg
  src/components/Admin/AdminInstance/InstanceCreateModal/InstanceCreateModal.tsx
  src/components/Admin/AdminInstance/InstanceEditModal/InstanceEditModal.tsx
  src/components/Admin/AdminInstance/InstanceListComponent/InstanceListComponent.tsx
  src/components/Admin/AdminTopic/TopicCreateModal/TopicCreateModal.tsx
  src/components/Admin/AdminTopic/TopicEditModal/TopicEditModal.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx
  src/components/GitPullReqConnect/PullReq/PullReq.tsx
  src/components/GitPullReqConnect/PullReqExp/PullReqExp.tsx
  src/components/GitPullReqConnect/Repo/Repo.tsx
  src/components/GithubToken/GithubTokenInput.tsx
  src/components/SignUp/SignUpForm/SignUpName/SignUpName.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/constants/path.ts
  src/pages/Admin/AdminInstance/AdminInstance.tsx
  src/pages/Admin/AdminTopic/AdminTopic.tsx
  src/pages/GitPullReqConnect/GitPullReqConnect.tsx
  src/pages/MyPage/GithubToken/GithubToken.tsx
  src/pages/MyPage/GithubToken/githubTokenStyle.css
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
  src/types/adminType.ts
  src/types/githubTokenType.ts
Labels: enhancement
