Repository TeamTheGenius/TeamTheGenius_Web, pull requests merged in 2024-03, with the labels that each got.

#180 Feat: 마이페이지 탈퇴하기 UI 완성
  src/App.tsx
  src/components/MyPage/ServiceWithdraw/ReasonChoice/ReasonChoice.tsx
  src/components/MyPage/ServiceWithdraw/Title/Title.tsx
  src/components/MyPage/ServiceWithdraw/UnderLine/UnderLine.tsx
  src/components/MyPage/ServiceWithdraw/WithdrawButton/WithdrawButton.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/constants/path.ts
  src/pages/MyPage/GithubToken/GithubToken.tsx
  src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
  src/pages/MyPage/ServiceWithdraw/ServiceWithdraw.tsx
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
Labels: enhancement

#184 Feat: 신고페이지 UI 완성
  src/App.tsx
  src/assets/icon/gray-check.svg
  src/assets/icon/white-check.svg
  src/components/Certification/OthersAllCurrentCertification/ReportButton/ReportButton.tsx
  src/components/Certification/Report/OthersProfile/OthersProfile.tsx
  src/components/Certification/Report/ReportButton/ReportButton.tsx
  src/components/Certification/Report/ReportSelect/ReportSelect.tsx
  src/components/Certification/Report/Title/Title.tsx
  src/components/common/CertificationResult/CertificationResult.tsx
  src/constants/path.ts
  src/pages/Certification/Report/Report.tsx
Labels: enhancement

#188 fix: userEdit UI 수정, api type 경로 수정
  src/App.tsx
  src/apis/deleteAdminInstanceApi.ts
  src/apis/deleteAdminTopicApi.ts
  src/apis/getAdminDetailInstanceApi.ts
  src/apis/getAdminDetailTopicApi.ts
  src/apis/getAdminInstanceListApi.ts
  src/apis/getAdminTopicListApi.ts
  src/apis/patchAdminInstanceEditApi.ts
  src/apis/postAdminInstanceApi.ts
  src/apis/postAdminTopicApi.ts
  src/apis/postGithubTokenRegi.ts
  src/assets/icon/big-check-icon.svg
  src/assets/icon/big-sign-icon.svg
  src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
  src/pages/MyPage/InterestEdit/InterestEdit.tsx
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
Labels: bug, refactor

#190 feat: github api Test 완료
  src/apis/postGithubTokenRegi.ts
  src/components/GithubToken/GithubTokenInput.tsx
Labels: enhancement

#191 Feature/189 my challenge change UI
  src/assets/icon/success-stamp.svg
  src/components/Main/MyChallenge/MyChallengeLabel/MyChallengeLabel.tsx
  src/components/Main/MyChallenge/MyChallengeLinkWrap/MyChallengeLinkWrap.tsx
  src/components/Main/MyChallenge/MyChallengeTitle/MyChallengeTitle.tsx
  src/components/common/ChallengeItem/ChallengeItem.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
Labels: enhancement

#192 Feature/189 my challenge change UI
  src/App.tsx
  src/components/Main/MyChallenge/MyChallengeHeader/MyChallengeHeader.tsx
  src/components/Main/MyChallenge/MyChallengeLabel/MyChallengeLabel.tsx
  src/components/Main/MyChallenge/MyChallengeModal/MyChallengeModal.tsx
  src/components/common/Modal/Modal.tsx
  src/constants/path.ts
  src/hooks/useModal.ts
  src/index.css
  src/pages/Main/Main.tsx
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
  src/utils/breakLine.tsx
Labels: bug, enhancement

#193 refactor: bottomNav 공통 컴포넌트 수정 및 적용 user profile 공통 컴포넌트로 변경
  src/components/common/BottomButton/BottomButton.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
  src/pages/Payments/Fail/Fail.tsx
  src/pages/Payments/Payments.tsx
  src/pages/Payments/Success/Success.tsx
Labels: refactor

#197 Feature/166 certification page api - 1/2
  src/apis/getCertificationInformation .ts
  src/apis/getCertificationInstanceDetail .ts
  src/apis/getCertificationWeek.ts
  src/components/Certification/Certification/ChallengeInformation/ChallengeInformation.tsx
  src/components/Certification/MyCurrentCertification/CurrentAchivementRate/CurrentAchivementRate.tsx
  src/components/Certification/MyCurrentCertification/MyCertificationSummary/MyCertificationSummary.tsx
  src/components/Certification/MyCurrentCertification/MyRepository/MyRepository.tsx
  src/components/Certification/MyCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/Home/HorizontalScroll/HorizontalScroll.tsx
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/common/CertificationResult/CertificationResult.tsx
  src/data/myCertificationResultData.ts
  src/pages/Certification/Certification/Certification.tsx
  src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx
  src/utils/getIsToday.ts
Labels: enhancement

#201 Feat: 마이챌린지 - 시작 전 api 연결
  src/apis/getMyChallengePreActivity.ts
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
Labels: enhancement

#203 Feat: 마이챌린지 - 진행중 api 연결
  src/apis/getMyChallengeActivity.ts
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
Labels: enhancement

#205 Feat: 마이챌린지 - 완료 api 연결
  src/apis/getMyChallengeDone.ts
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
Labels: enhancement

#207 Feat: 마이챌린지 완료탭 보상 api 연결
  src/apis/getMyChallengeDoneReward.ts
  src/components/Main/MyChallenge/MyChallengeModal/MyChallengeModal.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
Labels: enhancement

#209 Feature/200 challenge detail button logic
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/constants/path.ts
  src/pages/ChallengeDetail/ChallengeDetail.tsx
Labels: enhancement

#211 Feature/200 challenge detail button logic
  src/components/ChallengeDetail/CoreInformation/CoreInformation.tsx
  src/pages/ChallengeDetail/ChallengeDetail.tsx
  vite.config.ts.timestamp-1709620885614-0178841895f2e.mjs
Labels: enhancement

#212 Feature/199 feat repo regi api
  package.json
  src/App.tsx
  src/apis/getGithubTokenApi.ts
  src/apis/getPullRequestVerifyApi.ts
  src/apis/getRepoVertifyApi.ts
  src/apis/getUserRepoApi.ts
  src/apis/postAdminTopicApi.ts
  src/apis/postChallengeRepoRegiApi.ts
  src/apis/postGithubTokenRegi.ts
  src/components/GitPullReqConnect/PullReq/PullReq.tsx
  src/components/GitPullReqConnect/PullReqExp/PullReqExp.tsx
  src/components/GitPullReqConnect/Repo/Repo.tsx
  src/components/GithubToken/GithubTokenInput.tsx
  src/components/common/BottomButton/BottomButton.tsx
  src/constants/path.ts
  src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
  src/pages/GitPullReqConnect/GitPullReqConnect.tsx
  src/types/githubTokenType.ts
  yarn.lock
Labels: enhancement

#218 feat: 포인트 상점 UI 제작
  package.json
  src/App.tsx
  src/assets/icon/icon_off_shop.svg
  src/assets/icon/icon_on_shop.svg
  src/assets/icon/shop-item-1.svg
  src/assets/icon/shop-item-2.svg
  src/components/MyPage/MyPage/MyPoint/MyPoint.tsx
  src/components/Shop/MobShopFrameSlice/MobShopFrameSlice.tsx
  src/components/Shop/ShopFrame/ShopFrame.tsx
  src/components/Shop/ShopHeader/ShopHeader.tsx
  src/components/Shop/ShopItem/ShopItem.tsx
  src/components/Shop/SubHeader/SubHeader.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/constants/path.ts
  src/data/shopFrameData.ts
  src/data/shopItemData.ts
  src/pages/Pet/Pet.tsx
  src/pages/Shop/Shop.tsx
  src/pages/Shop/swiperCustomStyle.css
  tailwind.config.js
  yarn.lock
Labels: enhancement

#219 Feature/210 mypage api
  src/apis/deleteLikeChallenge.ts
  src/apis/deleteServiceWithdraw.ts
  src/apis/getLikeChallenges.ts
  src/apis/getMyPageChallengesStatus.ts
  src/apis/getMyPageProfile.ts
  src/apis/postAuthLogout.ts
  src/assets/icon/heart-icon.svg
  src/assets/icon/temperature-indicator.svg
  src/components/MyPage/MyPage/MyChallengeSummary/MyChallengeSummary.tsx
  src/components/MyPage/MyPage/MyPoint/MyPoint.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/MyPage/MyPage/Temperature/Temperature.tsx
  src/components/MyPage/ServiceWithdraw/ReasonChoice/ReasonChoice.tsx
  src/components/MyPage/ServiceWithdraw/WithdrawButton/WithdrawButton.tsx
  src/components/MyPage/SettingMenu/LinkButton/LinkButton.tsx
  src/components/common/ChallengeItem/ChallengeItem.tsx
  src/components/common/Profile/Profile.tsx
  src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
  src/pages/MyPage/MyPage/MyPage.tsx
  src/pages/MyPage/ServiceWithdraw/ServiceWithdraw.tsx
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
Labels: enhancement

#221 Feature/215 feat mypage interest edit api
  src/apis/postInterestEditApi.ts
  src/components/MyPage/InterestEdit/InterestEditModal/InterestEditModal.tsx
  src/components/common/BottomButton/BottomButton.tsx
  src/components/common/Modal/Modal.tsx
  src/pages/MyPage/InterestEdit/InterestEdit.tsx
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
Labels: enhancement

#223 feat: myChallenge 인증패스 버튼 UI 및 모달 UI 추가했습니다.
  src/components/Main/MyChallenge/MyChallengeLabel/MyChallengeLabel.tsx
  src/components/Main/MyChallenge/MyChallengePass/MyChallengePassItem.tsx
  src/components/Main/MyChallenge/MyChallengeTitle/MyChallengeTitle.tsx
  src/components/Main/MyChallenge/MyChallengeWrap/MyChallengeWrap.tsx
  src/components/common/Modal/Modal.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengePassModal/MyChallengePassModal.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
Labels: enhancement, refactor

#226 Fix: 검색 페이지 버그 해결
  src/apis/getSearchedChallengeItem.ts
  src/components/Home/HomeHeader/HomeHeader.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/pages/Home/Search/ActivitySearch/ActivitySearch.tsx
  src/pages/Home/Search/AllSearch/AllSearch.tsx
  src/pages/Home/Search/DoneSearch/DoneSearch.tsx
  src/pages/Home/Search/PreActivitySearch/PreActivitySearch.tsx
  src/pages/Home/Search/Search.tsx
  src/pages/Main/Main.tsx
Labels: bug, enhancement

#227 Feature/222 feat mychallenge pass UI
  src/components/Main/MyChallenge/MyChallengeLabel/MyChallengeLabel.tsx
  src/components/Main/MyChallenge/MyChallengePass/MyChallengePassItem.tsx
  src/components/Main/MyChallenge/MyChallengeTitle/MyChallengeTitle.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
Labels: refactor

#230 Bugfix/228 solve dev error
  src/components/Main/MyChallenge/MyChallengeLabel/MyChallengeLabel.tsx
  src/components/Main/MyChallenge/MyChallengeLinkWrap/MyChallengeLinkWrap.tsx
  src/components/Main/MyChallenge/MyChallengeModal/CertificationPassModal/CertificationPassModal.tsx
  src/components/Main/MyChallenge/MyChallengePass/MyChallengePassItem.tsx
  src/components/Main/MyChallenge/MyChallengeTitle/MyChallengeTitle.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
Labels: bug

#233 Feat: 탈퇴 api 이유 추가
  src/apis/deleteServiceWithdraw.ts
  src/components/MyPage/ServiceWithdraw/WithdrawButton/WithdrawButton.tsx
Labels: enhancement

#232 Certification/166 certification api 3
  src/App.tsx
  src/apis/getMyWeekCertification.ts
  src/apis/getOthersWeekCertification.ts
  src/apis/getTotalCertification.ts
  src/components/Certification/Certification/Tabs/Tabs.tsx
  src/components/Certification/MyAllCurrentCertification/MyAllCertificationResult/MyAllCertificationResult.tsx
  src/components/Certification/MyCurrentCertification/MyAllCertificationLinkButton/MyAllCertificationLinkButton.tsx
  src/components/Certification/MyCurrentCertification/MyWeekCertification/MyThisWeekCertification.tsx
  src/components/Certification/MyCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/Certification/OthersAllCurrentCertification/OthersAllCertificationResult/OthersAllCertificationResult.tsx
  src/components/Certification/OthersCurrentCertification/OthersAllCertificationLinkButton/OthersAllCertificationLinkButton.tsx
  src/components/Certification/OthersCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/Certification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/Certification/TotalCertification/TotalCertification.tsx
  src/components/common/CertificationResult/CertificationResult.tsx
  src/constants/path.ts
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
  src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
  src/pages/Home/NewChallenge/NewChallenge.tsx
Labels: enhancement

#235 Feat: 인증 상세페이지 프로필 api 연결
  src/apis/postUserProfile.ts
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
Labels: enhancement

#242 Feature/241 delete challenge participation
  src/apis/deleteChallengeParticipation.ts
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/components/ChallengeDetail/ChallengeDetailModal/ParticipationCancelAskModal/ParticipationCancelAskModal.tsx
  src/components/ChallengeDetail/ParticipationCancelButton/ParticipationCancelButton.tsx
  src/components/Main/MyChallenge/MyChallengeModal/CertificationPassModal/CertificationPassModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardModal/GetRewardModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardTwiceModal/GetRewardTwiceModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/HasNoItemModal/HasNoItemModal.tsx
  src/components/common/Modal/Modal.tsx
  src/hooks/useModal.ts
  src/pages/ChallengeDetail/ChallengeDetail.tsx
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyPage/InterestEdit/InterestEdit.tsx
Labels: bug, enhancement

#245 Feat: 링크 모달 UI
  src/assets/icon/blue-link-icon.svg
  src/components/Admin/AdminInstance/InstanceCreateModal/InstanceCreateModal.tsx
  src/components/Certification/CertificationModal/CertificationPRLinkModal/CertificationPRLinkModal.css
  src/components/Certification/CertificationModal/CertificationPRLinkModal/CertificationPRLinkModal.tsx
  src/components/Certification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/Certification/TotalCertification/TotalCertification.tsx
  src/components/common/Modal/Modal.tsx
  src/hooks/useModal.ts
Labels: bug, enhancement

#247 feat: instance 인증 방법 추가
  src/apis/postAdminInstanceApi.ts
  src/components/Admin/AdminInstance/InstanceCreateModal/InstanceCreateModal.tsx
  src/components/Admin/AdminInstance/InstanceEditModal/InstanceEditModal.tsx
  src/components/Admin/AdminInstance/InstanceListComponent/InstanceListComponent.tsx
  src/components/Admin/AdminInstance/InstanceListComponent/InstanceTitle/InstanceTitle.tsx
  src/components/Admin/AdminTopic/TopicEditModal/TopicEditModal.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicTitle/TopicTitle.tsx
  src/components/MyPage/InterestEdit/InterestCheckEdit/InterestCheckEdit.tsx
  src/utils/modalCard.tsx
Labels: enhancement

#248 Fix: 로그아웃 로직 오류 수정
  src/apis/postAuthLogout.ts
  src/pages/Auth/Auth.tsx
  src/pages/LogIn/LogIn.tsx
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
Labels: bug

#250 Feat: 좋아요 토글 연결
  src/apis/postLikeChallenge.ts
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/pages/ChallengeDetail/ChallengeDetail.tsx
  src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
Labels: enhancement

#252 Feat: item endpoint 수정
  src/apis/getMyChallengeDoneReward.ts
  src/apis/postPassCertification.ts
  src/apis/postUseItem.ts
  src/components/Main/MyChallenge/MyChallengeModal/CertificationPassModal/CertificationPassModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardTwiceModal/GetRewardTwiceModal.tsx
  src/pages/ChallengeDetail/ChallengeDetail.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
Labels: enhancement

#253 Refactor/249 refactor axios instance
  src/apis/axios/axios.ts
  src/apis/axios/request.ts
  src/apis/deleteAdminInstanceApi.ts
  src/apis/deleteAdminTopicApi.ts
  src/apis/deleteChallengeParticipation.ts
  src/apis/deleteLikeChallenge.ts
  src/apis/deleteServiceWithdraw.ts
  src/apis/getAdminDetailInstanceApi.ts
  src/apis/getAdminDetailTopicApi.ts
  src/apis/getAdminInstanceListApi.ts
  src/apis/getAdminTopicListApi.ts
  src/apis/getCertificationInformation .ts
  src/apis/getCertificationInstanceDetail .ts
  src/apis/getCheckNicknameApi.ts
  src/apis/getGithubTokenApi.ts
  src/apis/getInstanceDetail.ts
  src/apis/getInterestTags.ts
  src/apis/getLatestChallenge.ts
  src/apis/getLikeChallenges.ts
  src/apis/getMyChallengeActivity.ts
  src/apis/getMyChallengeDone.ts
  src/apis/getMyChallengeDoneReward.ts
  src/apis/getMyChallengePreActivity.ts
  src/apis/getMyPageChallengesStatus.ts
  src/apis/getMyPageProfile.ts
  src/apis/getMyWeekCertification.ts
  src/apis/getOthersWeekCertification.ts
  src/apis/getPopularChallenge.ts
  src/apis/getPullRequestVerifyApi.ts
  src/apis/getRecommendedChallenge.ts
  src/apis/getRepoVertifyApi.ts
  src/apis/getSearchedChallengeItem.ts
  src/apis/getTotalCertification.ts
  src/apis/getUserRepoApi.ts
  src/apis/patchAdminInstanceEditApi.ts
  src/apis/patchAdminTopicEditApi.ts
  src/apis/postAdminInstanceApi.ts
  src/apis/postAdminTopicApi.ts
  src/apis/postAuthLogout.ts
  src/apis/postChallengeRepoRegiApi.ts
  src/apis/postGithubTokenRegi.ts
  src/apis/postInterestEditApi.ts
  src/apis/postJWTApi.ts
  src/apis/postLikeChallenge.ts
  src/apis/postPaymentData.ts
  src/apis/postPaymentFail.ts
  src/apis/postPaymentSuccess.ts
  src/apis/postSignUpApi.ts
  src/apis/postTodayCertification.ts
  src/apis/postUseItem.ts
  src/apis/postUserInfoEdit.ts
  src/apis/postUserProfile.ts
  src/components/Admin/AdminInstance/InstanceEditModal/InstanceEditModal.tsx
  src/constants/url.ts
Labels: refactor

#257 Feature/256 UUID UI
  src/assets/icon/copy-icon.svg
  src/components/Certification/MyCurrentCertification/CurrentAchivementRate/CurrentAchivementRate.tsx
  src/components/Certification/MyCurrentCertification/PRTemplate/PRTemplate.tsx
  src/components/Certification/TotalCertification/TotalCertification.tsx
  src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx
Labels: bug, enhancement

#259 Feat: 회원가입 시 랜덤 기본 프로필 이미지 적용
  src/apis/deleteServiceWithdraw.ts
  src/apis/postSignUpApi.ts
  src/assets/image/basic-profile-image-blue.png
  src/assets/image/basic-profile-image-gray.png
  src/assets/image/basic-profile-image-green.png
  src/assets/image/basic-profile-image-orange.png
  src/assets/image/basic-profile-image-pink.png
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/pages/Interest/Interest.tsx
Labels: enhancement

#263 Feature/262 certification UI add/edit
  src/assets/icon/bordered-blue-right-arrow-icon.svg
  src/components/Certification/CertificationModal/CertificationPRLinkModal/CertificationPRLinkModal.css
  src/components/Certification/CertificationModal/CertificationPRLinkModal/CertificationPRLinkModal.tsx
  src/components/Certification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/Certification/TotalCertification/TotalCertification.tsx
  src/components/common/CertificationResult/CertificationResult.tsx
  src/hooks/useModal.ts
Labels: enhancement

#261 Feat 인증페이지 UUID api 연결
  src/components/Certification/MyCurrentCertification/PRTemplate/PRTemplate.tsx
  src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx
Labels: enhancement

#267 Feature/254 shop api
  src/apis/axios/request.ts
  src/apis/getItemAllApi.ts
  src/apis/getItemFrameApi.ts
  src/apis/getItemPassApi.ts
  src/apis/postGithubTokenRegi.ts
  src/apis/postItemEquipApi.ts
  src/apis/postItemUnEquipApi.ts
  src/apis/postUserInfoEdit.ts
  src/apis/postdItemBuyApi.ts
  src/assets/image/frame_0.svg
  src/assets/image/frame_1.svg
  src/assets/image/pass_0.svg
  src/assets/image/pass_1.svg
  src/components/GithubToken/GithubTokenInput.tsx
  src/components/MyPage/MyPage/MyPoint/MyPoint.tsx
  src/components/Shop/MobShopFrameSlice/MobShopFrameSlice.tsx
  src/components/Shop/ShopFrame/ShopFrame.tsx
  src/components/Shop/ShopFrameList/MobShopFrameSlice/MobShopFrameSlice.tsx
  src/components/Shop/ShopFrameList/ShopFrame/ShopFrame.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameButton/ShopFrameButton.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameImg/ShopFrameImg.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameItem.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameName/ShopFrameName.tsx
  src/components/Shop/ShopItem/ShopItem.tsx
  src/components/Shop/ShopModal/ShopBuyModal/ShopBuyModal.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteEquip/ShopCompleteEquip.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteFrame/ShopCompleteFrame.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteNonePoint/ShopCompleteNonePoint.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompletePass/ShopCompletePass.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompletedModal.tsx
  src/components/Shop/ShopPassItem/ShopPass.tsx
  src/components/Shop/ShopPassItem/ShopPassItem/ShopPassCost/ShopPassCost.tsx
  src/components/Shop/ShopPassItem/ShopPassItem/ShopPassCount/ShopPassCount.tsx
  src/components/Shop/ShopPassItem/ShopPassItem/ShopPassImg/ShopPassImg.tsx
  src/components/Shop/ShopPassItem/ShopPassItem/ShopPassItem.tsx
  src/components/Shop/ShopPassItem/ShopPassItem/ShopPassName/ShopPassName.tsx
  src/components/common/Modal/Modal.tsx
  src/data/shopItemData.ts
  src/pages/Shop/Shop.tsx
  src/types/shopType.ts
Labels: enhancement

#270 Feat: 프로필프레임 UI 완성
  src/assets/icon/profile-frame-christmas.svg
  src/assets/icon/profile-frame-power-of-dark.svg
  src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx
  src/components/Certification/MyCurrentCertification/MyWeekCertification/MyThisWeekCertification.tsx
  src/components/Certification/OthersAllCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/Certification/OthersCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/Certification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/MyPage/MyPage/Header/Header.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/MyPage/MyPage/Temperature/Temperature.tsx
  src/components/common/Profile/Profile.tsx
  src/hooks/useModal.ts
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
  src/pages/Home/NewChallenge/NewChallenge.tsx
Labels: enhancement

#272 Feature/271 profile frame api
  src/apis/postItemEquipApi.ts
  src/apis/postItemUnEquipApi.ts
  src/apis/postJWTApi.ts
  src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx
  src/components/Certification/OthersAllCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/Certification/OthersCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/common/Header/Header.tsx
  src/constants/localStorageKey.ts
  src/pages/Auth/Auth.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
  src/pages/Shop/Shop.tsx
Labels: bug, enhancement

#274 feat: 결제 내역 api 연동
  src/App.tsx
  src/apis/axios/request.ts
  src/apis/getPaymentReceiptApi.ts
  src/constants/path.ts
  src/hooks/useNumberFormat.ts
  src/pages/MyPage/Receipt/Receipt.tsx
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
Labels: enhancement

#281 Bugfix: 보상 api 연결 오류 해결
  src/apis/getMyChallengeDoneReward.ts
Labels: bug

#283 Bugfix: 전체 인증 현황 조회 array length 예외 처리
  src/components/Certification/TotalCertification/TotalCertification.tsx
Labels: bug

#285 Bugfix: 마이페이지 헤더 불일치, 링크 라벨 불일치 해결
  src/components/MyPage/MyPage/LinkButtons/LinkButtons.tsx
  src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
  src/pages/MyPage/InterestEdit/InterestEdit.tsx
Labels: bug

#287 refacotr: github token ui 수정
  src/components/GithubToken/GithubTokenInput.tsx
Labels: refactor

#286 feat: 어드민 페이지 보안
  src/components/Admin/AdminTopic/TopicCreateModal/TopicCreateModal.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx
  src/components/Error/ErrorHeader/ErrorHeader.tsx
  src/pages/Admin/AdminInstance/AdminInstance.tsx
  src/pages/Admin/AdminTopic/AdminTopic.tsx
  src/pages/Auth/Auth.tsx
  src/pages/error/Error.tsx
Labels: enhancement

#288 feat: crypto instanceId, idenfier, frameId 적용
  package.json
  src/App.tsx
  src/apis/postItemEquipApi.ts
  src/apis/postJWTApi.ts
  src/apis/postLikeChallenge.ts
  src/apis/postSignUpApi.ts
  src/components/Admin/AdminTopic/TopicCreateModal/TopicCreateModal.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/components/GithubToken/GithubTokenInput.tsx
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/Main/MyChallenge/MyChallengeLinkWrap/MyChallengeLinkWrap.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/MyPage/MyPage/UserEdit/UserImg/UserImg.tsx
  src/hooks/useCrypto.ts
  src/pages/Admin/AdminInstance/AdminInstance.tsx
  src/pages/Auth/Auth.tsx
  src/pages/ChallengeDetail/ChallengeDetail.tsx
  src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
  src/pages/MyPage/GithubToken/GithubToken.tsx
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
  yarn.lock
Labels: enhancement

#296 Feature/295 crypto
  src/components/Certification/Certification/ChallengeDetailLinkButton/ChallengeDetailLinkButton.tsx
  src/components/Certification/Certification/ChallengeInformation/ChallengeInformation.tsx
  src/components/Certification/Certification/Tab/Tab.tsx
  src/components/Certification/Certification/Tabs/Tabs.tsx
  src/components/Certification/MyCurrentCertification/MyAllCertificationLinkButton/MyAllCertificationLinkButton.tsx
  src/components/Certification/OthersCurrentCertification/OthersAllCertificationLinkButton/OthersAllCertificationLinkButton.tsx
  src/components/Certification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/Certification/TotalCertification/TotalCertification.tsx
  src/components/Main/MyChallenge/MyChallengeLinkWrap/MyChallengeLinkWrap.tsx
  src/components/common/VerticalChallengeItems/VerticalChallengeItems.tsx
  src/hooks/useCrypto.ts
  src/pages/Certification/Certification/Certification.tsx
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
  src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
Labels: enhancement

#298 Refactor/291 refactor integration test
  src/apis/postUserInfoEdit.ts
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/components/MyPage/MyPage/UserEdit/InfoInput/InfoInput.tsx
  src/components/MyPage/MyPage/UserEdit/UserPreview/UserPreview.tsx
  src/components/common/NickNameInput/NickNameInput.tsx
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
Labels: refactor

#299 Fix: jwt 유효 않을 때 처리
  src/App.tsx
  src/apis/axios/AxiosNavigation.tsx
  src/components/Route/PrivateRoute/PrivateRoute.tsx
  src/pages/Auth/Auth.tsx
  src/pages/error/Error.tsx
Labels: bug

#300 refactor: state 오류 수정
  src/components/common/NickNameInput/NickNameInput.tsx
Labels: refactor
