Repository TeamTheGenius/TeamTheGenius_Web, pull requests merged in 2024-05, with the labels that each got.

#370 refactor: mutate isLoading 적용, 노션 링크 적용
  src/apis/patchAdminInstanceEditApi.ts
  src/apis/patchAdminTopicEditApi.ts
  src/apis/postAdminInstanceApi.ts
  src/hooks/queries/useAdminInstanceQuery.ts
  src/hooks/queries/useAdminTopicQuery.ts
  src/hooks/queries/useGithubQuery.ts
  src/pages/Admin/AdminInstance/InstanceCreate/InstanceCreate.tsx
  src/pages/Admin/AdminInstance/InstanceEdit/InstanceEdit.tsx
  src/pages/Admin/AdminTopic/TopicCreate/TopicCreate.tsx
  src/pages/Admin/AdminTopic/TopicEdit/TopicEdit.tsx
  src/pages/MyPage/GithubToken/GithubToken.tsx
  src/types/adminType.ts
Labels: refactor

#373 Fix: multipart 에러 해결
  package.json
  src/apis/axios/axios.ts
  src/apis/patchAdminInstanceFileEditApi.ts
  src/apis/patchAdminTopicEditFileApi.ts
  src/apis/patchProfileImage.ts
  src/apis/postAdminInstanceFileApi.ts
  src/apis/postPaymentSuccess.ts
  src/apis/postProfileImage.ts
  src/components/LogIn/GithubLoginButton/index.tsx
  src/components/MyPage/InterestChallenge/InfiniteInterestChallenge/InfiniteInterestChallenge.tsx
  src/hooks/queries/useHomeInstanceQuery.ts
  src/setupProxy.js
Labels: bug

#376 Refactor/369 global status modal
  package.json
  src/App.tsx
  src/apis/axios/axios.ts
  src/apis/postPaymentSuccess.ts
  src/components/Certification/CertificationModal/CertificationPRLinkModal/CertificationPRLinkModal.tsx
  src/components/Certification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/Certification/TotalCertification/TotalCertification.tsx
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/components/ChallengeDetail/ChallengeDetailModal/ParticipationCancelAskModal/ParticipationCancelAskModal.tsx
  src/components/ChallengeDetail/ParticipationCancelButton/ParticipationCancelButton.tsx
  src/components/Common/NickNameInput/NickNameInput.tsx
  src/components/Error/CommonGetErrorFallback/CommonGetErrorFallback.tsx
  src/components/GitPullReqConnect/PullReq/PullReq.tsx
  src/components/GitPullReqConnect/Repo/Repo.tsx
  src/components/LogIn/GithubLoginButton/index.tsx
  src/components/Main/MyChallenge/MyChallengeModal/AskGetRewardTwiceModal/AskGetRewardTwiceModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/CertificationModal/CertificationModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/CertificationPassModal/CertificationPassModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardModal/GetRewardModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardTwiceModal/GetRewardTwiceModal.tsx
  src/components/MyPage/InterestChallenge/InfiniteInterestChallenge/InfiniteInterestChallenge.tsx
  src/components/MyPage/InterestEdit/InterestTagEditFrom/InterestTagEditFrom.tsx
  src/components/MyPage/ServiceWithdraw/WithdrawButton/WithdrawButton.tsx
  src/components/MyPage/UserInfoEdit/UserInformationEditForm/UserInformationEditForm.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameButton/ShopFrameButton.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameImg/ShopFrameImg.tsx
  src/components/Shop/ShopModal/ShopBuyModal/ShopBuyModal.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteEquip/ShopCompleteEquip.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteFrame/ShopCompleteFrame.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteTicket/ShopCompleteTicket.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompletedModal.tsx
  src/components/Shop/ShopTicketList/ShopTicketItem/ShopTicketItem.tsx
  src/components/SignUp/SignUpForm/SignUpForm.tsx
  src/hooks/useModal.ts
  src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
  src/pages/Interest/Interest.tsx
  src/pages/Modal/Modal.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
  src/pages/Payments/Payments.tsx
  src/setupProxy.js
  src/stores/modalStore.ts
  yarn.lock
Labels: refactor

#378 Refactor/377 seperate mutation error handle
  src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx
  src/components/Certification/OthersAllCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/components/ChallengeDetail/ChallengeDetailModal/ParticipationCancelAskModal/ParticipationCancelAskModal.tsx
  src/components/Common/NickNameInput/NickNameInput.tsx
  src/components/Error/CommonMutationErrorModal/CommonMutationErrorModal.tsx
  src/components/GitPullReqConnect/PullReq/PullReq.tsx
  src/components/GitPullReqConnect/Repo/Repo.tsx
  src/components/GithubToken/GithubTokenInput.tsx
  src/components/Main/MyChallenge/MyChallengeModal/CertificationModal/CertificationModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/CertificationPassModal/CertificationPassModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardModal/GetRewardModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardTwiceModal/GetRewardTwiceModal.tsx
  src/components/MyPage/InterestChallenge/InfiniteInterestChallenge/InfiniteInterestChallenge.tsx
  src/components/MyPage/InterestEdit/InterestCheckEdit/InterestCheckEdit.tsx
  src/components/MyPage/InterestEdit/InterestTagEditFrom/InterestTagEditFrom.tsx
  src/components/MyPage/ServiceWithdraw/WithdrawButton/WithdrawButton.tsx
  src/components/Shop/ShopFrameList/MobShopFrameSlice/MobShopFrameSlice.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameButton/ShopFrameButton.tsx
  src/components/Shop/ShopFrameList/ShopFrameList.tsx
  src/components/Shop/ShopModal/ShopBuyModal/ShopBuyModal.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteFrame/ShopCompleteFrame.tsx
  src/components/Shop/ShopTicketList/ShopTicketList.tsx
  src/hooks/queries/useAdminInstanceQuery.tsx
  src/hooks/queries/useAdminTopicQuery.tsx
  src/hooks/queries/useAuthQuery.tsx
  src/hooks/queries/useCertificationQuery.tsx
  src/hooks/queries/useFileQuery.tsx
  src/hooks/queries/useGithubQuery.tsx
  src/hooks/queries/useInstanceDetailQuery.tsx
  src/hooks/queries/useItemQuery.tsx
  src/hooks/queries/useLikeQuery.tsx
  src/hooks/queries/useMyChallengeQuery.tsx
  src/hooks/queries/useProfileQuery.tsx
  src/hooks/queries/useUserQuery.tsx
  src/pages/Admin/AdminInstance/AdminInstance.tsx
  src/pages/Admin/AdminInstance/InstanceCreate/InstanceCreate.tsx
  src/pages/Admin/AdminInstance/InstanceEdit/InstanceEdit.tsx
  src/pages/Admin/AdminTopic/AdminTopic.tsx
  src/pages/Admin/AdminTopic/TopicCreate/TopicCreate.tsx
  src/pages/Admin/AdminTopic/TopicEdit/TopicEdit.tsx
  src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
  src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
  src/pages/Interest/Interest.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
Labels: refactor

#379 Feat: 어드민 페이지 errorBoundary 설정
  src/components/Admin/AdminInstance/InstanceListComponent/AdminInstanceContent/AdminInstanceContent.tsx
  src/components/Admin/AdminInstance/InstanceListComponent/InstanceListComponent.tsx
  src/components/Admin/AdminLayOut/AdminListLayOut/AdminListLayOut.tsx
  src/components/Admin/AdminTopic/TopicListComponent/AdminTopicContent/AdminTopicContent.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx
  src/components/Error/ErrorHeader/ErrorHeader.tsx
  src/hooks/queries/useAdminInstanceQuery.tsx
  src/hooks/queries/useAdminTopicQuery.tsx
  src/pages/Admin/AdminInstance/AdminInstance.tsx
  src/pages/Admin/AdminTopic/AdminTopic.tsx
  src/pages/Error/Error.tsx
Labels: enhancement

#381 Feature/380 image none substitution
  src/assets/image/basicChallengeImage.jpg
  src/components/Certification/Certification/ChallengeImage/ChallengeImage.tsx
  src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx
  src/components/Certification/OthersAllCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/ChallengeDetail/Image/Image.tsx
  src/components/Common/ChallengeItem/ChallengeItem.tsx
  src/components/Common/Profile/Profile.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
Labels: enhancement

#384 Feat: 세로 스크롤 고정
  src/index.css
Labels: enhancement

#386 Bug fix/instance edit
  src/pages/Admin/AdminInstance/InstanceEdit/InstanceEdit.tsx
Labels: bug
