Repository TeamTheGenius/TeamTheGenius_Web, pull requests merged in 2024-04, with the labels that each got.

#302 Feat: 인증 갱신 실패 시 모달 띄우기
  src/apis/postTodayCertification.ts
  src/components/Certification/CertificationModal/CertificationFailModal/CertificationFailModal.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
Labels: enhancement

#304 Fix: 참가자 인증 내역 조회 시 버그 해결
  src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx
  src/components/Certification/OthersCurrentCertification/OthersAllCertificationLinkButton/OthersAllCertificationLinkButton.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
Labels: bug

#306 Reafactor/305 loading suspense
  src/App.tsx
  src/components/Home/HomeHeader/HomeHeader.tsx
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/MyPage/MyPage/MyChallengeSummary/MyChallengeSummary.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/layout/HomeLayout/HomeLayout.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/NewChallenge/NewChallenge.tsx
  src/pages/Home/PopularChallenge/PopularChallenge.tsx
  src/pages/Home/Search/ActivitySearch/ActivitySearch.tsx
  src/pages/Home/Search/AllSearch/AllSearch.tsx
  src/pages/Home/Search/DoneSearch/DoneSearch.tsx
  src/pages/Home/Search/PreActivitySearch/PreActivitySearch.tsx
  src/pages/Home/Search/Search.tsx
  src/pages/Home/SuggestionChallenge/SuggestionChallenge.tsx
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
  src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
  src/pages/MyPage/MyPage/MyPage.tsx
Labels: refactor

#307 feature: userEdit modal 적용 및 로딩 컴포넌트 수정
  src/apis/postUserInfoEdit.ts
  src/components/MyPage/EditModal/EditModal.tsx
  src/components/MyPage/InterestEdit/InterestEditModal/InterestEditModal.tsx
  src/pages/MyPage/InterestEdit/InterestEdit.tsx
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
Labels: enhancement

#312 Feature/311 error component
  package.json
  src/App.tsx
  src/components/Certification/ThisWeekCertification/ThisWeekCertification.tsx
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/components/Error/PrivateRouteErrorFallback/PrivateRouteErrorFallback.tsx
  src/components/GitPullReqConnect/GitTokenCheckIcon/GitTokenCheckIcon.tsx
  src/components/GithubToken/GithubTokenInput.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardModal/GetRewardModal.tsx
  src/components/Route/PrivateRoute/PrivateRoute.tsx
  src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/error/Error.tsx
  yarn.lock
Labels: enhancement

#313 feat: header link ui 변경된 사항으로 업데이트
  src/apis/getPullRequestVerifyApi.ts
  src/assets/icon/alarm.svg
  src/components/Admin/AdminInstance/InstanceCreateModal/InstanceCreateModal.tsx
  src/components/GitPullReqConnect/GitPullReqModal/GitPullReqModal.tsx
  src/components/GitPullReqConnect/PullReq/PullReq.tsx
  src/components/GitPullReqConnect/PullReqExp/PullReqExp.tsx
  src/components/Home/HomeHeader/HomeHeader.tsx
  src/components/Main/MyChallenge/MyChallengeHeader/MyChallengeHeader.tsx
  src/components/common/MainHeader/MainHeader.tsx
  src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyPage/MyPage/MyPage.tsx
  src/pages/Shop/Shop.tsx
Labels: bug, enhancement, refactor

#315 Feat: 프로필 기본 이미지 설정
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
Labels: enhancement

#316 refactor: header 수정
  src/components/Main/MyChallenge/MyChallengeHeader/MyChallengeHeader.tsx
  src/components/common/MainHeader/MainHeader.tsx
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyPage/MyPage/MyPage.tsx
  src/pages/Shop/Shop.tsx
Labels: refactor

#318 Fix: 헤더 z-index 높이기
  src/components/common/MainHeader/MainHeader.tsx
Labels: bug

#320 Refactor: 쿼리키 상수화
  src/components/Certification/Certification/ChallengeInformation/ChallengeInformation.tsx
  src/components/Common/MainHeader/MainHeader.tsx
  src/components/GithubToken/GithubTokenInput.tsx
  src/components/Home/HomeHeader/HomeHeader.tsx
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/MyPage/InterestEdit/InterestCheckEdit/InterestCheckEdit.tsx
  src/components/MyPage/MyPage/MyChallengeSummary/MyChallengeSummary.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/common/MainHeader/MainHeader.tsx
  src/constants/queryKey.ts
  src/constants/url.ts
  src/pages/Auth/Auth.tsx
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
  src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
  src/pages/ChallengeDetail/ChallengeDetail.tsx
  src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
  src/pages/Home/NewChallenge/NewChallenge.tsx
  src/pages/Home/PopularChallenge/PopularChallenge.tsx
  src/pages/Home/Search/ActivitySearch/ActivitySearch.tsx
  src/pages/Home/Search/AllSearch/AllSearch.tsx
  src/pages/Home/Search/DoneSearch/DoneSearch.tsx
  src/pages/Home/Search/PreActivitySearch/PreActivitySearch.tsx
  src/pages/Home/SuggestionChallenge/SuggestionChallenge.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
  src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
  src/pages/MyPage/Receipt/Receipt.tsx
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
  src/pages/Shop/Shop.tsx
Labels: refactor

#322 Refactor/321 seperate business logic
  src/apis/deleteServiceWithdraw.ts
  src/apis/patchAdminTopicEditApi.ts
  src/apis/postInterestEditApi.ts
  src/apis/postUserInfoEdit.ts
  src/apis/postdItemBuyApi.ts
  src/components/Admin/AdminInstance/InstanceCreateModal/InstanceCreateModal.tsx
  src/components/Admin/AdminInstance/InstanceEditModal/InstanceEditModal.tsx
  src/components/Admin/AdminTopic/TopicEditModal/TopicEditModal.tsx
  src/components/MyPage/InterestEdit/InterestCheckEdit/InterestCheckEdit.tsx
  src/components/MyPage/MyPage/MyChallengeSummary/MyChallengeSummary.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/MyPage/MyPage/UserEdit/UserImg/UserImg.tsx
  src/components/MyPage/MyPage/UserEdit/UserName/UserName.tsx
  src/components/MyPage/ServiceWithdraw/WithdrawButton/WithdrawButton.tsx
  src/hooks/queries/useProfileQuery.ts
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/MyPage/InterestEdit/InterestEdit.tsx
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
  src/pages/Shop/Shop.tsx
  src/types/interestTagsType.ts
  src/types/myProfileData.ts
  src/types/profileType.ts
Labels: refactor

#324 Refactor/321 seperate business logic
  src/App.tsx
  src/apis/deleteChallengeParticipation.ts
  src/apis/postAuthLogout.ts
  src/apis/postChallengeRepoRegiApi.ts
  src/apis/postItemEquipApi.ts
  src/apis/postItemUnEquipApi.ts
  src/apis/postdItemBuyApi.ts
  src/components/ChallengeDetail/Bottom/Bottom.tsx
  src/components/ChallengeDetail/ChallengeDetailModal/ParticipationCancelAskModal/ParticipationCancelAskModal.tsx
  src/components/ChallengeDetail/ParticipationCancelButton/ParticipationCancelButton.tsx
  src/components/Common/MainHeader/MainHeader.tsx
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/Main/MyChallenge/MyChallengeModal/CertificationPassModal/CertificationPassModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardTwiceModal/GetRewardTwiceModal.tsx
  src/components/Shop/ShopModal/ShopBuyModal/ShopBuyModal.tsx
  src/components/common/MainHeader/MainHeader.tsx
  src/constants/queryKey.ts
  src/hooks/queries/useAuthQuery.ts
  src/hooks/queries/useHomeInstanceQuery.ts
  src/hooks/queries/useInstanceDetailQuery.ts
  src/hooks/queries/useItemQuery.ts
  src/hooks/queries/useLikeQuery.ts
  src/pages/Admin/AdminInstance/AdminInstance.tsx
  src/pages/Admin/AdminTopic/AdminTopic.tsx
  src/pages/Auth/Auth.tsx
  src/pages/ChallengeDetail/ChallengeDetail.tsx
  src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
  src/pages/Home/NewChallenge/NewChallenge.tsx
  src/pages/Home/PopularChallenge/PopularChallenge.tsx
  src/pages/Home/Search/ActivitySearch/ActivitySearch.tsx
  src/pages/Home/Search/AllSearch/AllSearch.tsx
  src/pages/Home/Search/DoneSearch/DoneSearch.tsx
  src/pages/Home/Search/PreActivitySearch/PreActivitySearch.tsx
  src/pages/Home/SuggestionChallenge/SuggestionChallenge.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
  src/pages/MyPage/SettingMenu/SettingMenu.tsx
  src/pages/Shop/Shop.tsx
  src/types/homeInstance.ts
  src/types/instanceDetail.ts
  src/types/likeType.ts
Labels: refactor

#326 bug: userEdit 모달 컴포넌트 추가 및 작동 순서 조정, 무한 로딩 픽스
  src/apis/getCheckNicknameApi.ts
  src/apis/postSignUpApi.ts
  src/components/MyPage/EditModal/EditModal.tsx
  src/components/MyPage/MyPage/UserEdit/UserPreview/UserPreview.tsx
  src/components/common/BottomNav/bottomNavStyle.css
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
  tsconfig.json
Labels: bug

#325 bug: 닉네임 중복체크 오류 수정
  src/apis/axios/request.ts
  src/apis/getCheckNicknameApi.ts
  src/components/Common/BottomNav/BottomNav.tsx
  src/components/Common/BottomNav/bottomNavStyle.css
  src/components/Common/Loading/Loading.tsx
  src/components/Common/NickNameInput/NickNameInput.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/components/common/BottomNav/bottomNavStyle.css
  src/components/common/Loading/Loading.tsx
  src/components/common/NickNameInput/NickNameInput.tsx
  src/pages/Interest/Interest.tsx
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
  tsconfig.json
Labels: bug

#327 Refactor/321 seperate business logic
  src/components/Certification/Certification/ChallengeInformation/ChallengeInformation.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardTwiceModal/GetRewardTwiceModal.tsx
  src/hooks/queries/useCertificationQuery.ts
  src/hooks/queries/useGithubQuery.ts
  src/hooks/queries/useMyChallengeQuery.ts
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
  src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
  src/types/certificationType.ts
  src/types/myChallengeType.ts
Labels: refactor

#330 bug: pr 확인 모달 정상 작동 안되던 현상 수정
  src/apis/getPullRequestVerifyApi.ts
  src/components/GitPullReqConnect/GitPullReqModal/GitPullReqModal.tsx
  src/components/GitPullReqConnect/PullReq/PullReq.tsx
  src/components/common/BottomNav/bottomNavStyle.css
  src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
Labels: bug

#333 bug: nickName check 수정
  src/apis/getCheckNicknameApi.ts
  src/components/Common/NickNameInput/NickNameInput.tsx
  src/components/SignUp/SignUpForm/SignUpForm.tsx
  src/components/SignUp/SignUpForm/SignUpModal/SignUpModal.tsx
  src/components/common/NickNameInput/NickNameInput.tsx
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
Labels: bug

#334 Refactor/332 loading logic
  src/apis/postUseItem.ts
  src/components/Certification/Certification/ChallengeImage/ChallengeImage.tsx
  src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx
  src/components/Certification/MyAllCurrentCertification/MyProfile/MyTotalCertification.tsx
  src/components/Certification/OthersAllCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/Certification/OthersAllCurrentCertification/OthersProfile/OthersTotalCertification.tsx
  src/components/ChallengeDetail/ChallengeDetailContent/ChallengeDetailContent.tsx
  src/components/ChallengeDetail/ChallengeDetailModal/ParticipationCancelAskModal/ParticipationCancelAskModal.tsx
  src/components/Common/Loading/Loading.tsx
  src/components/Common/Loading/LoadingBox/LoadingBox.tsx
  src/components/Error/PrivateRouteErrorFallback/PrivateRouteErrorFallback.tsx
  src/components/LogIn/GithubLoginButton/index.tsx
  src/components/Main/MyChallenge/MyChallengeHeader/MyChallengeHeader.tsx
  src/components/Main/MyChallenge/MyChallengeModal/AskGetRewardTwiceModal/AskGetRewardTwiceModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/CertificationModal/CertificationModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/CertificationPassModal/CertificationPassModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/CertificationResultModal/CertificationResultModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardModal/GetRewardModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardResultModal/GetRewardResultModal.tsx
  src/components/Main/MyChallenge/MyChallengeModal/GetRewardTwiceModal/GetRewardTwiceModal.tsx
  src/components/MyPage/MyPage/MyPoint/MyPoint.tsx
  src/components/Route/PrivateRoute/PrivateRoute.tsx
  src/components/Shop/ShopFrameList/MobShopFrameSlice/MobShopFrameSlice.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameButton/ShopFrameButton.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameImg/ShopFrameImg.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameItem.tsx
  src/components/Shop/ShopFrameList/ShopFrameList.tsx
  src/components/Shop/ShopModal/ShopBuyModal/ShopBuyModal.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteEquip/ShopCompleteEquip.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteFrame/ShopCompleteFrame.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteNonePoint/ShopCompleteNonePoint.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteTicket/ShopCompleteTicket.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompletedModal.tsx
  src/components/Shop/ShopTicketList/ShopTicketItem/ShopTicketItem.tsx
  src/components/Shop/ShopTicketList/ShopTicketList.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/Loading/LoadingBox/LoadingBox.tsx
  src/hooks/queries/useAuthQuery.ts
  src/hooks/queries/useCertificationQuery.ts
  src/hooks/queries/useInstanceDetailQuery.ts
  src/hooks/queries/useItemQuery.ts
  src/hooks/queries/useMyChallengeQuery.ts
  src/hooks/queries/useProfileQuery.ts
  src/hooks/queries/useUserQuery.ts
  src/pages/Auth/Auth.tsx
  src/pages/Certification/Certification/Certification.tsx
  src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
  src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
  src/pages/ChallengeDetail/ChallengeDetail.tsx
  src/pages/Interest/Interest.tsx
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyPage/InterestEdit/InterestEdit.tsx
  src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
  src/pages/Shop/Shop.tsx
  src/types/shopType.ts
Labels: refactor

#336 Bugfix: jwt 만료 발생 시 에러 컴포넌트 안 사라짐
  src/App.tsx
  src/components/Error/PrivateRouteErrorFallback/PrivateRouteErrorFallback.tsx
  src/components/Route/PrivateRoute/PrivateRoute.tsx
Labels: bug

#338 Fix: 배포 404오류 해결
  vercel.json
Labels: bug

#339 Fix: 서버 url 변경
  package.json
  src/apis/axios/axios.ts
  src/apis/postPaymentSuccess.ts
  src/setupProxy.js
Labels: bug

#341 Fix: 서버 url 변경
  package.json
  src/apis/axios/axios.ts
  src/apis/postPaymentSuccess.ts
  src/components/LogIn/GithubLoginButton/index.tsx
  src/setupProxy.js
Labels: bug

#345 Fix: 로고 깜빡임 문제 해결
  src/components/ChallengeDetail/Image/Image.tsx
  src/components/Common/MainHeader/MainHeader.tsx
  src/components/Home/HomeHeader/HomeHeader.tsx
  src/components/MyPage/MyPage/MyPoint/MyPoint.tsx
  src/components/common/MainHeader/MainHeader.tsx
  src/layout/HomeLayout/HomeLayout.tsx
  src/pages/Home/Search/Search.tsx
  src/pages/Shop/Shop.tsx
  tailwind.config.js
Labels: bug

#347 Fix: 에러 컴포넌트 안사라지는 문제 해결
  package.json
  src/App.tsx
  src/apis/axios/axios.ts
  src/apis/postPaymentSuccess.ts
  src/components/Error/PrivateRouteErrorFallback/PrivateRouteErrorFallback.tsx
  src/components/LogIn/GithubLoginButton/index.tsx
  src/components/Route/PrivateRoute/PrivateRoute.tsx
  src/setupProxy.js
Labels: bug

#342 feature: payments 개발 중 안내 모달
  src/components/Shop/ShopModal/ShopTestModal/ShopTestModal.tsx
  src/pages/Shop/Shop.tsx
Labels: enhancement

#350 refactor: payments modal 수정
  src/components/Payments/PaymentsGoods/PaymentsGoods.tsx
  src/components/Payments/PaymentsModal/PaymentsModal.tsx
  src/components/Payments/PaymentsPayInfo/PaymentsPayInfo.tsx
  src/pages/Payments/Payments.tsx
  src/pages/Shop/Shop.tsx
Labels: refactor

#363 Refactor: 무한 스크롤 로직 수정
  src/App.tsx
  src/components/Common/VerticalChallengeItems/VerticalChallengeItems.tsx
  src/components/Error/CommonGetErrorFallback/CommonGetErrorFallback.tsx
  src/components/Home/InfiniteActivitySearchedChallenge/InfiniteActivitySearchedChallenge.tsx
  src/components/Home/InfiniteAllSearchedChallenge/InfiniteAllSearchedChallenge.tsx
  src/components/Home/InfiniteDoneSearchedChallenge/InfiniteDoneSearchedChallenge.tsx
  src/components/Home/InfiniteNewChallenge/InfiniteNewChallenge.tsx
  src/components/Home/InfinitePopularChallenge/InfinitePopularChallenge.tsx
  src/components/Home/InfinitePreActivitySearchedChallenge/InfinitePreActivitySearchedChallenge.tsx
  src/components/Home/InfiniteRecommededChallenge/InfiniteRecommededChallenge.tsx
  src/components/MyPage/InterestChallenge/InfiniteInterestChallenge/InfiniteInterestChallenge.tsx
  src/components/MyPage/Receipt/PaymentList/PaymentList.tsx
  src/hooks/queries/useAdminInstanceQuery.ts
  src/hooks/queries/useAdminTopicQuery.ts
  src/hooks/queries/useCertificationQuery.ts
  src/hooks/queries/useHomeInstanceQuery.ts
  src/hooks/queries/useInstanceDetailQuery.ts
  src/hooks/queries/useItemQuery.ts
  src/hooks/queries/useLikeQuery.ts
  src/hooks/queries/useMyChallengeQuery.ts
  src/hooks/queries/useProfileQuery.ts
  src/pages/Admin/AdminInstance/InstanceCreate/InstanceCreate.tsx
  src/pages/Admin/AdminInstance/InstanceEdit/InstanceEdit.tsx
  src/pages/Admin/AdminTopic/TopicCreate/TopicCreate.tsx
  src/pages/Admin/AdminTopic/TopicEdit/TopicEdit.tsx
  src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
  src/types/homeInstance.ts
Labels: refactor

#365 Feat: 빈 데이터일 때 보여줄 컴포넌트 적용
  src/assets/icon/gray-exclamation-mark.svg
  src/assets/icon/gray-fire-hatch-icon.svg
  src/assets/icon/gray-heart-harch-icon.svg
  src/assets/icon/gray-search-icon.svg
  src/assets/icon/gray-wind-fallen-leaves-icon.svg
  src/components/Common/EmptyDataView/EmptyDataView.tsx
  src/components/Home/EmptyDataComponent/EmptyDataComponent.tsx
  src/components/Home/InfiniteActivitySearchedChallenge/InfiniteActivitySearchedChallenge.tsx
  src/components/Home/InfiniteAllSearchedChallenge/InfiniteAllSearchedChallenge.tsx
  src/components/Home/InfiniteDoneSearchedChallenge/InfiniteDoneSearchedChallenge.tsx
  src/components/Home/InfiniteNewChallenge/InfiniteNewChallenge.tsx
  src/components/Home/InfinitePopularChallenge/InfinitePopularChallenge.tsx
  src/components/Home/InfinitePreActivitySearchedChallenge/InfinitePreActivitySearchedChallenge.tsx
  src/components/Home/InfiniteRecommededChallenge/InfiniteRecommededChallenge.tsx
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/MyPage/InterestChallenge/InfiniteInterestChallenge/InfiniteInterestChallenge.tsx
  src/components/MyPage/Receipt/PaymentList/PaymentList.tsx
  src/components/MyPage/UserInfoEdit/UserInformationEditForm/UserInformationEditForm.tsx
  src/pages/Home/Search/Search.tsx
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
  src/pages/MyPage/Receipt/Receipt.tsx
  vite.config.ts.timestamp-1706365008730-32e21a7d5a264.mjs
  vite.config.ts.timestamp-1709620885614-0178841895f2e.mjs
  vite.config.ts.timestamp-1713413142060-363647473fed4.mjs
Labels: enhancement

#367 Refactor/360 refactor separate admih file api
  src/apis/getAdminInstanceListApi.ts
  src/apis/getAdminTopicListPageApi.ts
  src/apis/patchAdminInstanceEditApi.ts
  src/apis/patchAdminInstanceFileEditApi.ts
  src/apis/patchAdminTopicEditApi.ts
  src/apis/patchAdminTopicEditFileApi.ts
  src/apis/postAdminInstanceApi.ts
  src/apis/postAdminInstanceFileApi.ts
  src/apis/postAdminTopicApi.ts
  src/apis/postAdminTopicFileApi.ts
  src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx
  src/data/InterestData.ts
  src/hooks/queries/useAdminInstanceQuery.ts
  src/hooks/queries/useAdminTopicQuery.ts
  src/pages/Admin/AdminInstance/AdminInstance.tsx
  src/pages/Admin/AdminInstance/InstanceCreate/InstanceCreate.tsx
  src/pages/Admin/AdminInstance/InstanceEdit/InstanceEdit.tsx
  src/pages/Admin/AdminTopic/AdminTopic.tsx
  src/pages/Admin/AdminTopic/TopicCreate/TopicCreate.tsx
  src/pages/Admin/AdminTopic/TopicEdit/TopicEdit.tsx
  src/pages/Interest/Interest.tsx
  src/types/adminType.ts
Labels: refactor
