Repository TeamTheGenius/TeamTheGenius_Web, pull requests merged in 2024-01, with the labels that each got.

#58 Feature/57 change filename
  src/App.tsx
  src/components/Error/ErrorHeader/ErrorHeader.tsx
  src/components/Interest/InterestButton/InterestBtn.tsx
  src/components/Interest/InterestCheck/InterestCheck.tsx
  src/components/Interest/InterestHeader/InterestHeader.tsx
  src/components/Interest/InterestInputButton/InterestInputBtn.tsx
  src/components/Interest/InterestInputModal/InterestInputModal.tsx
  src/components/Interest/InterestModalHeader/InterestModalHeader.tsx
  src/components/Interest/InterestModalInput/InterestModalInput.tsx
  src/components/Interest/InterestPromptModal/InterestPromptModal.tsx
  src/components/Landing/Button/Button.tsx
  src/components/Landing/Comment/Comment.tsx
  src/components/Landing/Image/Image.tsx
  src/components/LogIn/Button/Button.tsx
  src/components/LogIn/Buttons/Buttons.tsx
  src/components/LogIn/Comment/Comment.tsx
  src/components/LogIn/FacebookButton/FacebookButton.tsx
  src/components/LogIn/GoogleButton/GoogleButton.tsx
  src/components/LogIn/Image/Image.tsx
  src/components/LogIn/KakaoButton/KakaoButton.tsx
  src/components/LogIn/NaverButton/NaverButton.tsx
  src/components/LogIn/TermsOfService/TermsOfService.tsx
  src/components/SignUp/SignUpHeader/SignUpHeader.tsx
  src/components/SignUp/SignUpInput/SignUpInput.tsx
  src/pages/Interest/Interest.tsx
  src/pages/Landing/Landing.tsx
  src/pages/LogIn/GoogleOauth/GoogleOauth.tsx
  src/pages/LogIn/KakaoOauth/KakaoOauth.tsx
  src/pages/LogIn/LogIn.tsx
  src/pages/SignComplete/SignComplete.tsx
  src/pages/error/Error.tsx
  src/pages/signUp/SignUp.tsx
Labels: enhancement

#61 Rename: 파일, 폴더 이름 변경
  src/App.css
  src/App.tsx
  src/assets/image/complete-icon.png
  src/components/SignCompleteModal/SignCompleteHeader/SignCompleteHeader.tsx
  src/components/SignCompleteModal/SignCompleteModal.tsx
  src/main.tsx
  src/pages/Interest/Interest.tsx
  src/pages/Landing/Landing.tsx
  src/pages/SignComplete/SignComplete.tsx
Labels: enhancement

#63 Feature/56 friends list component UI
  src/App.tsx
  src/assets/icon/circle-gradient-orange.svg
  src/assets/icon/circle-gradient.svg
  src/assets/icon/toggle.svg
  src/assets/image/temp/user1.jpg
  src/assets/image/temp/user2.jpg
  src/components/Main/FriendsInOnline/FriendsInOnline.tsx
  src/components/Main/FriendsInOnline/friendsInOnline.json
  src/components/Main/Underline/Underline.tsx
  src/components/Main/UserCircle/UserCircle.tsx
  src/pages/Main/Main.tsx
Labels: enhancement

#65 Feat: 회원가입 api 연동 가입완료 modal 구현
  package.json
  src/components/SignCompleteModal/SignCompleteModal/SignCompleteModal.tsx
  src/components/SignCompleteModal/SignCompletePropModal/SignCompletePropsModal.tsx
  src/components/SignUp/SignUpInput/SignUpInput.tsx
  src/pages/Interest/Interest.tsx
  src/pages/Main/Main.tsx
  src/pages/signUp/SignUp.tsx
  src/setupProxy.js
  yarn.lock
Labels: enhancement

#67 Refactor: font-pretendard 전체 적용 후 중복된 코드 삭제
  src/components/Error/ErrorHeader/ErrorHeader.tsx
  src/components/Interest/InterestButton/InterestBtn.tsx
  src/components/Interest/InterestHeader/InterestHeader.tsx
  src/components/Interest/InterestModalHeader/InterestModalHeader.tsx
  src/components/Interest/InterestModalInput/InterestModalInput.tsx
  src/components/Landing/Comment/Comment.tsx
  src/components/LogIn/Comment/Comment.tsx
  src/components/LogIn/TermsOfService/TermsOfService.tsx
  src/components/Main/UserCircle/UserCircle.tsx
  src/components/SignCompleteModal/SignCompleteHeader/SignCompleteHeader.tsx
  src/components/SignUp/SignUpHeader/SignUpHeader.tsx
  src/components/SignUp/SignUpInput/SignUpInput.tsx
  src/components/common/Button.tsx
  src/index.css
Labels: refactor

#68 Docs: 코드 리팩토링 이슈를 위한 템플릿입니다.
  .github/ISSUE_TEMPLATE/refactor-template.md
Labels: documentation

#74 Feature: 어드민 페이지 초기 작업 완성
  src/App.tsx
  src/components/Admin/AdminInstance/InstanceCreateModal/InstanceCreateModal.tsx
  src/components/Admin/AdminInstance/InstanceCreateModal/antdCheck.css
  src/components/Admin/AdminInstance/InstanceEditModal/InstanceEditModal.tsx
  src/components/Admin/AdminInstance/InstanceListComponent/InstanceListComponent.tsx
  src/components/Admin/AdminTopic/TopicCreateModal/TopicCreateModal.tsx
  src/components/Admin/AdminTopic/TopicEditModal/TopicEditModal.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx
  src/components/Admin/CreateBtn/CreateBtn.tsx
  src/components/Admin/Title/Title.tsx
  src/pages/Admin/AdminInstance/AdminInstance.tsx
  src/pages/Admin/AdminTopic/AdminTopic.tsx
  src/utils/modalCard.tsx
Labels: enhancement

#79 Feat: SCcoreDream 폰트 세팅
  index.html
  src/index.css
  tailwind.config.js
Labels: enhancement

#81 Feat: 프로필 페이지 관심사 선택페이지 UI 수정
  src/components/Admin/AdminInstance/InstanceCreateModal/InstanceCreateModal.tsx
  src/components/Admin/AdminInstance/InstanceCreateModal/antdCheck.module.css
  src/components/Interest/InterestButton/InterestBtn.tsx
  src/components/Interest/InterestCheck/InterestCheck.tsx
  src/components/Interest/InterestCheck/antdCheckbox.css
  src/components/Interest/InterestHeader/InterestHeader.tsx
  src/components/Interest/InterestInputModal/InterestInputModal.tsx
  src/components/Interest/InterestModalInput/InterestModalInput.tsx
  src/components/SignUp/SignUpForm/SignUpForm.tsx
  src/components/SignUp/SignUpForm/SignUpInput/SignUpInput.tsx
  src/components/SignUp/SignUpHeader/SignUpHeader.tsx
  src/index.css
  src/pages/Interest/Interest.tsx
  src/pages/Interest/antdCheckbox.css
  src/pages/Interest/interests.json
  src/pages/signUp/SignUp.tsx
  tailwind.config.js
Labels: enhancement

#82 Feature/80 login page UI
  src/assets/icon/github-mark.svg
  src/assets/image/facebook-logo.png
  src/assets/image/hero.jpg
  src/assets/image/kakao-logo.png
  src/assets/image/naver-logo.png
  src/components/LogIn/Button/Button.tsx
  src/components/LogIn/Buttons/Buttons.tsx
  src/components/LogIn/Comment/Comment.tsx
  src/components/LogIn/FacebookButton/FacebookButton.tsx
  src/components/LogIn/GithubLoginButton/index.tsx
  src/components/LogIn/GoogleButton/GoogleButton.tsx
  src/components/LogIn/Image/Image.tsx
  src/components/LogIn/KakaoButton/KakaoButton.tsx
  src/components/LogIn/NaverButton/NaverButton.tsx
  src/components/LogIn/TermsOfService/TermsOfService.tsx
  src/index.css
  src/pages/LogIn/LogIn.tsx
Labels: enhancement

#84 Feature/83 homepage home tab UI
  src/App.tsx
  src/assets/icon/next-icon.svg
  src/assets/icon/person-icon.svg
  src/components/Main/ChallengeItem/ChallengeItem.tsx
  src/components/Main/FriendsInOnline/FriendsInOnline.tsx
  src/components/Main/FriendsInOnline/friendsInOnline.json
  src/components/Main/Home/Home.tsx
  src/components/Main/HorizontalScroll/HorizontalScroll.tsx
  src/components/Main/MoreButton/MoreButton.tsx
  src/components/Main/NewChallenge/NewChallenge.tsx
  src/components/Main/PopularChallenge/PopularChallenge.tsx
  src/components/Main/SuggestionChallenge/SuggestionChallenge.tsx
  src/components/Main/Tab/Tab.tsx
  src/components/Main/Tabs/Tabs.tsx
  src/components/Main/Title/Title.tsx
  src/components/Main/Underline/Underline.tsx
  src/components/Main/UserCircle/UserCircle.tsx
  src/components/common/MobCard.tsx
  src/data/pupularChallengeData.ts
  src/data/suggestionChallengeData.ts
  src/index.css
  src/pages/Main/Main.tsx
  src/utils/mergeTailwind.ts
Labels: enhancement

#87 Feature/86 homepage each tabpage UI
  src/components/Main/ChallengeItem/ChallengeItem.tsx
  src/components/Main/FilterButton/FilterButton.tsx
  src/components/Main/FilterButtons/FilterButtons.tsx
  src/components/Main/Home/Home.tsx
  src/components/Main/NewChallenge/NewChallenge.tsx
  src/components/Main/PopularChallenge/PopularChallenge.tsx
  src/components/Main/SuggestionChallenge/SuggestionChallenge.tsx
  src/components/Main/VerticalChallengeItems/VerticalChallengeItems.tsx
  src/data/newChallengeData.ts
  src/data/pupularChallengeData.ts
  src/pages/Main/Main.tsx
  tailwind.config.js
Labels: enhancement

#89 Refactor: loginMobCard 생성
  src/components/common/LoginMobCard.tsx
  src/components/common/MobCard.tsx
  src/index.css
  src/pages/Interest/Interest.tsx
  src/pages/Landing/Landing.tsx
  src/pages/LogIn/LogIn.tsx
  src/pages/signUp/SignUp.tsx
Labels: refactor

#101 Refactor: 경로 상수화
  src/App.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx
  src/components/Landing/Button/Button.tsx
  src/components/Main/MainHeader/MainHeader.tsx
  src/components/Main/MoreButton/MoreButton.tsx
  src/components/Main/Tab/Tab.tsx
  src/components/Main/Tabs/Tabs.tsx
  src/components/SignUp/SignUpForm/SignUpForm.tsx
  src/constants/path.ts
  src/pages/Interest/Interest.tsx
  src/pages/Main/Home/Home.tsx
Labels: refactor

#104 Feature/94 menu icon
  src/assets/icon/icon_off_1.png
  src/assets/icon/icon_off_2.png
  src/assets/icon/icon_off_3.png
  src/assets/icon/icon_off_4.png
  src/assets/icon/icon_on_1.png
  src/assets/icon/icon_on_2.png
  src/assets/icon/icon_on_3.png
  src/assets/icon/icon_on_4.png
  src/components/common/BottomNav/BottomNav.tsx
  src/components/common/BottomNav/BottomNavStyle.css
  src/pages/Main/Main.tsx
Labels: enhancement

#106 Feature/105 change mainpage
  src/App.tsx
  src/assets/icon/icon_off_1.png
  src/assets/icon/icon_off_2.png
  src/assets/icon/icon_off_3.png
  src/assets/icon/icon_off_4.png
  src/assets/icon/icon_off_home.svg
  src/assets/icon/icon_off_myChallenge.svg
  src/assets/icon/icon_off_myPage.svg
  src/assets/icon/icon_off_pet.svg
  src/assets/icon/icon_on_1.png
  src/assets/icon/icon_on_2.png
  src/assets/icon/icon_on_3.png
  src/assets/icon/icon_on_4.png
  src/assets/icon/icon_on_home.svg
  src/assets/icon/icon_on_myChallenge.svg
  src/assets/icon/icon_on_myPage.svg
  src/assets/icon/icon_on_pet.svg
  src/components/Main/MoreButton/MoreButton.tsx
  src/components/Main/Tabs/Tabs.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/components/common/BottomNav/BottomNavStyle.css
  src/constants/path.ts
  src/data/newChallengeData.ts
  src/pages/Interest/Interest.tsx
  src/pages/Main/Home/Home.tsx
  src/pages/Main/HomeTab/Home.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/MyChallenge/MyChallenge.tsx
  src/pages/Main/MyPage/MyPage.tsx
  src/pages/Main/NewChallengeTab/NewChallenge.tsx
  src/pages/Main/Pet/Pet.tsx
  src/pages/Main/PopularChallengeTab/PopularChallenge.tsx
  src/pages/Main/Search/Search.tsx
  src/pages/Main/SuggestionChallengeTab/SuggestionChallenge.tsx
  src/pages/Main/TabContent/TabContent.tsx
Labels: enhancement, refactor

#108 Feature/107 refactor signup interest UI
  src/assets/icon/nickname_X.svg
  src/components/Interest/InterestButton/InterestBtn.tsx
  src/components/Interest/InterestCheck/InterestCheck.tsx
  src/components/SignUp/SignUpForm/SignUpForm.tsx
  src/components/SignUp/SignUpForm/SignUpInput/SignUpDesc.tsx
  src/components/SignUp/SignUpForm/SignUpName/SignUpName.tsx
  src/components/SignUp/SignUpHeader/SignUpHeader.tsx
  src/components/common/LoginMobCard.tsx
  src/pages/Interest/Interest.tsx
  src/pages/Interest/api/SignUpApi.ts
  src/pages/LogIn/LogIn.tsx
  src/pages/signUp/SignUp.tsx
  src/pages/signUp/api/CheckNicknameApi.ts
  src/pages/signUp/signUpStyle.css
  vite.config.ts.timestamp-1706365008730-32e21a7d5a264.mjs
Labels: enhancement, refactor

#114 Refactor/113 change home page structure
  src/App.tsx
  src/components/Home/HomeHeader/HomeHeader.tsx
  src/components/Home/HorizontalScroll/HorizontalScroll.tsx
  src/components/Home/MoreButton/MoreButton.tsx
  src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx
  src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx
  src/components/Home/Tab/Tab.tsx
  src/components/Home/Tabs/Tabs.tsx
  src/components/Home/Title/Title.tsx
  src/components/Main/Tabs/Tabs.tsx
  src/components/Search/FilterButton/FilterButton.tsx
  src/components/Search/FilterButtons/FilterButtons.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/components/common/ChallengeItem/ChallengeItem.tsx
  src/components/common/VerticalChallengeItems/VerticalChallengeItems.tsx
  src/constants/path.ts
  src/layout/HomeLayout/HomeLayout.tsx
  src/pages/Home/Home.tsx
  src/pages/Main/Home/Home.tsx
  src/pages/Main/HomeTab/Home.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/NewChallengeTab/NewChallenge.tsx
  src/pages/Main/PopularChallengeTab/PopularChallenge.tsx
  src/pages/Main/Search/Search.tsx
  src/pages/Main/SuggestionChallengeTab/SuggestionChallenge.tsx
  src/pages/Main/TabContent/TabContent.tsx
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/NewChallenge/NewChallenge.tsx
  src/pages/Pet/Pet.tsx
  src/pages/PopularChallenge/PopularChallenge.tsx
  src/pages/Search/Search.tsx
  src/pages/SuggestionChallenge/SuggestionChallenge.tsx
Labels: enhancement, refactor

#117 Feat: 로그인 api 연결
  src/App.tsx
  src/apis/getCheckNicknameApi.ts
  src/apis/postJWTApi.ts
  src/apis/postSignUpApi.ts
  src/components/Landing/Button/Button.tsx
  src/components/Landing/Comment/Comment.tsx
  src/components/Landing/Image/Image.tsx
  src/components/LogIn/GithubLoginButton/index.tsx
  src/components/SignUp/SignUpForm/SignUpName/SignUpName.tsx
  src/constants/localStorageKey.ts
  src/constants/path.ts
  src/pages/Interest/Interest.tsx
  src/pages/Landing/Landing.tsx
  src/pages/LogIn/LogIn.tsx
Labels: enhancement, refactor
