Repository TeamTheGenius/TeamTheGenius_Web, pull requests merged in 2024-06, with the labels that each got.

#387 Refactor/day check
  src/pages/Admin/AdminInstance/InstanceCreate/InstanceCreate.tsx
Labels: refactor

#389 Feature/388 remove topic image
  src/components/Admin/AdminInstance/InstanceListComponent/InstanceListComponent.tsx
  src/components/Admin/AdminInstance/InstanceListComponent/InstanceTitle/InstanceTitle.tsx
  src/components/Admin/AdminLayOut/AdminFormLayOut/AdminFormLayOut.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx
  src/components/Admin/AdminTopic/TopicListComponent/TopicTitle/TopicTitle.tsx
  src/components/Admin/CreateBtn/CreateBtn.tsx
  src/hooks/queries/useAdminInstanceQuery.tsx
  src/pages/Admin/AdminInstance/InstanceCreate/InstanceCreate.tsx
  src/pages/Admin/AdminInstance/InstanceEdit/InstanceEdit.tsx
  src/pages/Admin/AdminTopic/TopicCreate/TopicCreate.tsx
  src/pages/Admin/AdminTopic/TopicEdit/TopicEdit.tsx
Labels: enhancement

#391 Bugfix: 깃허브 토큰 등록 후 연달아 깃허브 토큰 확인하기
  src/components/GithubToken/GithubTokenInput.tsx
  src/hooks/queries/useGithubQuery.tsx
  src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
  src/types/githubTokenType.ts
Labels: bug

#395 Feat: refresh-token 만료 시 identifier 삭제
  src/components/Error/CommonGetErrorFallback/CommonGetErrorFallback.tsx
  src/components/Error/CommonMutationErrorModal/CommonMutationErrorModal.tsx
  src/components/Shop/ShopFrameList/MobShopFrameSlice/MobShopFrameSlice.tsx
  src/components/Shop/ShopFrameList/ShopFrameList.tsx
Labels: enhancement

#404 Feature/396 vercel cicd yml
  .github/workflows/CI.yml
Labels: documentation, enhancement

#403 Fix: 마이챌린지 에러바운더리 분리
  package.json
  src/apis/axios/axios.ts
  src/apis/postPaymentSuccess.ts
  src/components/LogIn/GithubLoginButton/index.tsx
  src/components/Main/MyChallenge/MyChallengeActivityList/MyChallengeActivityList.tsx
  src/components/Main/MyChallenge/MyChallengeDoneList/MyChallengeDoneList.tsx
  src/components/Main/MyChallenge/MyChallengePreActivityList/MyChallengePreActivityList.tsx
  src/index.css
  src/pages/MyChallenge/MyChallenge.tsx
  src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
  src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
  src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
  src/setupProxy.js
  yarn.lock
Labels: bug

#405 Feat: profile frame 추가
  src/apis/postItemEquipApi.ts
  src/assets/icon/profile-frame-fire.svg
  src/assets/icon/profile-frame-ghost.svg
  src/assets/icon/profile-frame-pink-sticky.svg
  src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx
  src/components/Certification/OthersAllCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/Certification/OthersCurrentCertification/OthersProfile/OthersProfile.tsx
  src/components/Common/MainHeader/MainHeader.tsx
  src/components/Common/Profile/Profile.tsx
  src/components/Home/HomeHeader/HomeHeader.tsx
  src/components/Home/HorizontalScroll/HorizontalScroll.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/MyPage/MyPage/UserEdit/UserImg/UserImg.tsx
  src/components/Shop/ShopFrameList/MobShopFrameSlice/MobShopFrameSlice.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameButton/ShopFrameButton.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameImg/ShopFrameImg.tsx
  src/components/Shop/ShopFrameList/ShopFrameItem/ShopFrameItem.tsx
  src/components/Shop/ShopFrameList/ShopFrameList.tsx
  src/components/Shop/ShopModal/ShopCompletedModal/ShopCompleteFrame/ShopCompleteFrame.tsx
  src/components/Shop/ShopTicketList/ShopTicketList.tsx
  src/data/allChallengeData.ts
  src/data/frameData.ts
  src/data/newChallengeData.ts
  src/data/pupularChallengeData.ts
  src/data/shopFrameData.ts
  src/data/shopItemData.ts
  src/data/suggestionChallengeData.ts
  src/hooks/queries/useItemQuery.tsx
  src/pages/Shop/Shop.tsx
  tailwind.config.js
Labels: enhancement, refactor

#407 Feat: 마이페이지 온도 색상, 숫자 표시
  src/components/Common/LoginMobCard.tsx
  src/components/MyPage/MyPage/MyProfile/MyProfile.tsx
  src/components/MyPage/MyPage/Temperature/Temperature.tsx
Labels: enhancement

#409 Feat: 달성률 게이지 위에 현재까지 챌린지 달성률(%) 표시
  src/components/Certification/MyCurrentCertification/CurrentAchivementRate/CurrentAchivementRate.tsx
Labels: enhancement
